version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: beforeInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: applicationStart.sh
      timeout: 300
      runas: root
